### ISSUE TITLE
cryptopia not working

### ISSUE THREAD

**Issue by SoonCoin** [rudy4682/explorer#1]
the cryptopia market is not working.

getting an undefined is not an function error on line 97:28 of cryptopia.js

**Comment by rudy4682** [comment]
cryptopia_ID and market pair please

**Comment by SoonCoin** [comment]
"coin": "SOON",
    "exchange": "BTC",
    "enabled": ["bittrex", "cryptopia"],
    "cryptopia_id": "1762",
    "default": "bittrex"

**Comment by SoonCoin** [comment]
also when i used your files first i got on market tab this error but i fixed that i think.

views/markets/cryptopia.jade:29 27| td.hidden-xs #{marketdata.data.summary.ask} 28| td.hidden-xs #{marketdata.data.summary.last} > 29| - var cryptopia_change = (marketdata.data.summary.change).toFixed(4); 30| if cryptopia_change >= 0 31| td.success +#{cryptopia_change} % 32| else Cannot call method 'toFixed' of undefined

**Comment by SoonCoin** [comment]
in case you want the whole message:

TypeError: undefined is not a function
    at /root/soonexplorer2/lib/markets/cryptopia.js:97:28
    at Request._callback (/root/soonexplorer2/lib/markets/cryptopia.js:19:20)
    at Request.self.callback (/root/soonexplorer2/node_modules/request/request.js:121:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/root/soonexplorer2/node_modules/request/request.js:985:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/root/soonexplorer2/node_modules/request/request.js:936:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by rudy4682** [comment]
pm me from bitcointalk.org

**Comment by rudy4682** [comment]
Try the new commit and let me know
Sorry I forgot some touches

**Comment by rudy4682** [comment]
Resolved
